# Return to school COVID-19 rapid antigen testing in Newfoundland and Labrador {-}

1. Use the posters and CONSENT TO PARTICIPATE IN RESEARCH website for social media content. Download: [pdf](https://github.com/ahurford/website/blob/main/figures/School_Test_Poster.pdf) [pptx](https://github.com/ahurford/website/blob/main/figures/School_Test_Poster.pptx)

2. Ask permission from administrators prior to posting in Facebook groups.

3. Participation in the research study is voluntary. Do not use coersive language such as "_support_ our study". The purpose of advertisting is to provide the opportunity to participate.

4. Questions should be directed to Dr. Amy Hurford, (709) 864-8301, or Health Research Ethics Authority at (709) 777-6974 or info@hrea.ca.

5. Efforts should be made to advertise evenly across ethnic groups, in rural and urban communities, and across the entire province.

6. 1 survey is to be completed per household and the survey is to be completed by the parents or guardians of K-12 students.


