# Teaching {-}

## MATH 1006: Calculus for the Life Sciences {-}

[MATH 1000](https://www.mun.ca/university-calendar/st-johns-campus/faculty-of-science/13/9/) and _MATH 1006_ are credit restricted, and both are suitable pre-requisites for [MATH 1001: Calculus II](https://www.mun.ca/university-calendar/st-johns-campus/faculty-of-science/13/9/). _MATH 1006_ can take the place of the _MATH 1000_ program requirement for majors in Biochemistry, Biology, Chemistry, Psychology, Ocean Sciences, Kinesiology, and Physical Education. These calendar changes were approved by the Senate in September 2023, and will appear in the 2024-2025 University Calendar. Any student-friendly calendar change (such as this one), applies to all students immediately.

For a tentative MATH 1006 syllabus and content comparison to MATH 1000, see [here](https://github.com/ahurford/website/blob/main/MATH_1006.pdf).

---

#### Calendar description {-}

_MATH 1006. Calculus for Life Sciences_ is an introduction to differential calculus, including algebraic, trigonometric, exponential, logarithmic and inverse trigonometric functions. Applications include biomechanics, ecology, infectious diseases, physiology, and modelling.

CR: MATH 1000 and the former MATH 1081.

LC: 4 

PR: MATH 1090 or 109B or a combination of placement test and high school Mathematics scores acceptable to the Department 

UL: at most 9 credit hours in Mathematics will be given for courses successfully completed from the following list subject to normal credit restrictions: Mathematics 1000, 1005, 1006, 1031, 1050, 1051, the former 1080, the former 1081, 1090, 109A/B, the former 1150 and 1151.




